[package]
name = "mining-proxy"
version = "0.1.0"
authors = ["user"]
edition = "2018"

[dependencies]
codec_sv2 = { path = "../../../protocols/v2/codec-sv2", features=["noise_sv2"] }
messages_sv2 = { path = "../../../protocols/v2/messages-sv2" }
const_sv2 = { path = "../../../protocols/v2/const-sv2" }
async-channel = "1.5.1"
async-std = {version = "1.8.0", features = ["attributes"]}
binary_sv2 = { path = "../../../protocols/v2/binary-sv2/binary-sv2" }
network_helpers = { path = "../../../utils/network-helpers", features=["async_std"] }
buffer_sv2 = { path = "../../../utils/buffer"}
async-recursion = "0.3.2"
toml = {git = "https://github.com/diondokter/toml-rs", default-features = false, rev="c4161aa"}
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false}
futures = "0.3.19"
