[package]
name = "const_sv2"
version = "2.0.0"
authors = ["fi3 <email@email.org>"]
edition = "2018"
description = "This crate holds all of the shared constants used across the different Stratum V2 protocols and roles crates"
license = "MIT"
repository = "https://github.com/stratum-mining/stratum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = { version = "0.28.2", default-features = false, features =["hashes", "alloc","rand","rand-std"] }

#[dev-dependencies]
#cbindgen = "0.16.0"

[features]
no_std = []
