[workspace]

members = [
    "protocols/v1",
    # "protocols/v2/serde-sv2",
    "protocols/v2/binary-sv2/serde-sv2",
    "protocols/v2/binary-sv2/no-serde-sv2/codec",
    "protocols/v2/binary-sv2/no-serde-sv2/derive_codec",
    "protocols/v2/binary-sv2/binary-sv2",
    "protocols/v2/noise-sv2",
    "protocols/v2/framing-sv2",
    "protocols/v2/codec-sv2",
    "protocols/v2/const-sv2",
    "protocols/v2/subprotocols/common-messages",
    "protocols/v2/subprotocols/template-distribution",
    "utils/network-helpers",
    "utils/buffer",
    "examples/sv1-client-and-server",
    "examples/ping-pong-with-noise",
    "examples/ping-pong-without-noise",
]

exclude = ["vendor/ed25519-dalek"]
