[default]
features = "disable_nopanic prop_test noise_sv2 fuzz with_buffer_pool async_std debug tokio with_tokio derive_codec_sv2 binary_codec_sv2 default core"
run-types = [ "Lib" ]
exclude-files = [ "examples/*" ]
timeout = "120s"
fail-under = 20

[report]
out = ["Xml"]
