name: Benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Install dependencies
        run: cargo fetch

      - name: Start Server
        working-directory: ./benches/docker-foundationV2
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Run benchmarks
        working-directory: ./benches
        run: cargo bench

      - name: Stop Server
        if: always()
        run: docker-compose -f "docker-compose.yml" down

      - name: Publish benchmark results
        uses: actions-rs/cargo@v1
        with:
          command: bench