name: Benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65.0
          override: true

      - name: Install Valgrind && Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind=1:3.18.1-1ubuntu2 &&
          sudo apt-get install -y docker-compose


      - name: Install dependencies
        run: cargo fetch

      - name: Start Sv1 Server
        working-directory: ./benches/docker-foundationV2
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Start Sv2 Server
        id: start-server
        working-directory: ./roles/pool
        run: |
          nohup bash -c 'cargo run -- --c pool-config.toml > /dev/null 2>&1 &' && sleep 5
          echo "Server started successfully"

      - name: Run benchmarks
        working-directory: ./benches
        run: |
          cargo bench > output.txt

      - name: Get iai result
        working-directory: ./benches
        run: tail -n 15 output.txt > benchmark_results.txt

      - name: Publish benchmark result
        uses: actions/upload-artifact@v2
        with:
          name: benchmark_results
          path: |
           ./benches/benchmark_results.txt
           ./target/criterion

      - name: Stop Server
        working-directory: ./benches/docker-foundationV2
        run: docker-compose -f "docker-compose.yml" down
