# Runs all Message Generator tests in separate jobs

name: MG Test

on:
  pull_request:
    branches:
      - main

jobs:

  jds-do-not-fail-on-wrong-tsdatasucc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run jds-do-not-fail-on-wrong-tsdatasucc
        run: sh ./test/message-generator/test/jds-do-not-fail-on-wrong-tsdatasucc/jds-do-not-fail-on-wrong-tsdatasucc.sh

  sv1-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run sv1-test
        run: sh ./test/message-generator/test/sv1-test/sv1-test.sh

  mg-aggregate-results:
    name: "Aggregate MG Test Results"
    runs-on: ubuntu-latest
    if: always()
    needs: [
      jds-do-not-fail-on-wrong-tsdatasucc,
      sv1-test
    ]
    steps:
      - name: Aggregate Results
        run: |
          if [ "${{ needs.jds-do-not-fail-on-wrong-tsdatasucc.result }}" != "success" ] ||
          [ "${{ needs.sv1-test.result }}" != "success" ]; then
            echo "One or more jobs failed."
            exit 1
          else
            echo "All MG tests completed successfully"
          fi
