# This workflow is used to publish SV2 crates to cratesio

name: Release Libs

on: 
  # Manually run by going to "Actions/Release" in Github and running the workflow
  workflow_dispatch:

jobs:
  libs_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_DEPLOY_KEY }}
      - name: Publish crates common
        run: |
          cd common
          cargo publish
