# This workflow is used to publish SV2 crates to cratesio

name: Release Libs

on: 
  # Manually run by going to "Actions/Release" in Github and running the workflow
  workflow_dispatch:

jobs:
  libs_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_DEPLOY_KEY }}
      - name: Publish crates common
        continue-on-error: true
        run: |
          cd common
          cargo publish
      - name: Publish crates buffer_sv2
        continue-on-error: true
        run: |
          cd utils/buffer
          cargo publish
      - name: Publish crates no_serde_sv2_derive_codec
        continue-on-error: true
        run: |
          cd protocols/v2/binary-sv2/no-serde-sv2/derive_codec
          cargo publish
      - name: Publish crates no_serde_sv2_codec
        continue-on-error: true
        run: |
          cd protocols/v2/binary-sv2/no-serde-sv2/codec
          cargo publish
      - name: Publish crates serde_sv2
        continue-on-error: true
        run: |
          cd protocols/v2/binary-sv2/serde-sv2
          cargo publish
      - name: Publish crates binary_sv2
        continue-on-error: true
        run: |
          cd protocols/v2/binary-sv2/binary-sv2
          cargo publish
      - name: Publish crates v1
        continue-on-error: true
        run: |
          cd protocols/v1
          cargo publish
